(function () {
  'use strict';
  const USERS_KEY = 'skillbridge_users';
  const SESSION_KEY = 'skillbridge_session';
  const $ = (selector) => document.querySelector(selector);
  const getUsers = () => { try { return JSON.parse(localStorage.getItem(USERS_KEY)) || []; } catch { return []; } };
  const setMessage = (message, success) => { const el = $('#formMessage'); if (el) { el.textContent = message; el.style.color = success ? '#278260' : '#ca4d4d'; } };
  const initials = (name) => name.trim().split(/\s+/).slice(0,2).map(part => part[0]).join('').toUpperCase();
  const showToast = (message) => { const toast = $('#toast'); if (!toast) return; toast.textContent = message; toast.classList.add('show'); window.setTimeout(() => toast.classList.remove('show'), 2800); };
  const escapeHtml = (value) => value.replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));

  document.querySelectorAll('.visibility-toggle').forEach(button => button.addEventListener('click', () => {
    const input = button.previousElementSibling, showing = input.type === 'text'; input.type = showing ? 'password' : 'text'; button.textContent = showing ? 'Show' : 'Hide'; button.setAttribute('aria-label', showing ? 'Show password' : 'Hide password'); button.setAttribute('aria-pressed', String(!showing));
  }));
  const loginForm = $('#loginForm');
  if (loginForm) loginForm.addEventListener('submit', event => { event.preventDefault(); const email = $('#loginEmail').value.trim().toLowerCase(), password = $('#loginPassword').value; if (!email || !password) return setMessage('Please enter your email and password.'); const user = getUsers().find(item => item.email === email && item.password === password); if (!user) return setMessage('We could not find a matching account. Please register or check your details.'); localStorage.setItem(SESSION_KEY, JSON.stringify(user)); window.location.href = 'dashboard.html'; });
  const registerForm = $('#registerForm');
  if (registerForm) registerForm.addEventListener('submit', event => { event.preventDefault(); const name = $('#registerName').value.trim(), email = $('#registerEmail').value.trim().toLowerCase(), password = $('#registerPassword').value, confirm = $('#confirmPassword').value; if (name.length < 2) return setMessage('Please enter your full name.'); if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) return setMessage('Enter a valid email address.'); if (password.length < 6) return setMessage('Your password needs at least 6 characters.'); if (password !== confirm) return setMessage('Passwords do not match.'); const users = getUsers(); if (users.some(user => user.email === email)) return setMessage('An account already uses this email. Please sign in.'); const user = { name, email, password, scores: { interview: 35, aptitude: 68, technical: 52 } }; users.push(user); localStorage.setItem(USERS_KEY, JSON.stringify(users)); localStorage.setItem(SESSION_KEY, JSON.stringify(user)); window.location.href = 'dashboard.html'; });
  if (location.pathname.toLowerCase().endsWith('dashboard.html')) {
    let user; try { user = JSON.parse(localStorage.getItem(SESSION_KEY)); } catch { user = null; } if (!user || !user.name) { window.location.replace('index.html'); return; }
    const safeName = escapeHtml(user.name); ['studentName','greetingName'].forEach(id => { const el = document.getElementById(id); if (el) el.textContent = safeName; }); $('#avatarInitial').textContent = initials(user.name);
    const scores = user.scores || { interview: 35, aptitude: 68, technical: 52 }; const metrics = [{key:'interview',title:'Interview readiness',caption:'Practice interview confidence',icon:'◌',color:'purple'}, {key:'aptitude',title:'Aptitude score',caption:'Problem-solving ability',icon:'⌁',color:'orange'}, {key:'technical',title:'Technical skills',caption:'Applied skill proficiency',icon:'⌘',color:'teal'}];
    $('#metrics').innerHTML = metrics.map(metric => { const value = Math.max(0, Math.min(100, Number(scores[metric.key]) || 0)), isLow = value < 40; return `<article class="metric-card"><div class="metric-top"><span class="metric-icon ${metric.color}">${metric.icon}</span><span class="metric-status" style="color:${isLow ? '#d76c58' : '#3b9a7f'}">${isLow ? 'NEEDS FOCUS' : 'ON TRACK'}</span></div><h3>${metric.title}</h3><p>${metric.caption}</p><div class="metric-bottom"><strong>${value}%</strong><div class="tiny-progress"><span style="width:${value}%;background:${metric.color === 'orange' ? '#f49b48' : metric.color === 'teal' ? '#39aa9a' : '#6258d9'}"></span></div></div></article>`; }).join('');
    const overall = Math.round(metrics.reduce((total, metric) => total + (Number(scores[metric.key]) || 0), 0) / metrics.length); $('#overallValue').textContent = overall + '%'; $('#orbValue').textContent = overall + '%'; $('#overallBar').style.width = overall + '%'; $('#orbCircle').style.strokeDashoffset = String(320 - (320 * overall / 100));
    const low = metrics.filter(metric => (Number(scores[metric.key]) || 0) < 40); const recommendation = low.length ? `Your ${low.map(item => item.title.toLowerCase()).join(' and ')} ${low.length > 1 ? 'need' : 'needs'} attention. Practice consistently to build confidence before your next opportunity.` : 'You are on track across all three signals. Keep your weekly practice rhythm going to turn steady progress into confidence.'; const action = low.some(item => item.key === 'interview') ? 'Start interview practice →' : low.length ? 'Explore practice plan →' : 'Review your growth plan →'; $('#aiRecommendation').innerHTML = `<span class="ai-icon">✦</span><div><p class="eyebrow accent">SKILLBRIDGE AI INSIGHT</p><h2>${low.length ? 'A focused next step for you' : 'You are building strong momentum'}</h2><p>${recommendation}</p><button class="text-button placeholder-link">${action}</button></div>`;
    $('#profileButton').addEventListener('click', () => showToast('Profile settings will be available in the next phase.')); $('#menuButton')?.addEventListener('click', () => { const side = $('#sidebar'), open = side.classList.toggle('open'); $('#menuButton').setAttribute('aria-expanded', String(open)); }); document.querySelectorAll('.placeholder-link').forEach(item => item.addEventListener('click', event => { event.preventDefault(); $('#sidebar')?.classList.remove('open'); showToast('This section is coming in the next SkillBridge phase.'); }));
    const logout = document.createElement('button'); logout.className = 'text-button'; logout.type = 'button'; logout.textContent = 'Log out'; logout.style.cssText = 'position:absolute;bottom:19px;right:20px'; logout.addEventListener('click', () => { localStorage.removeItem(SESSION_KEY); location.href = 'index.html'; }); $('.sidebar').appendChild(logout);
  }
})();
